[package]
name = "simd"
version = "0.1.0"
authors = ["Huon Wilson <dbau.pp+github@gmail.com>"]

[dependencies]
serde = { version = "0.4", optional = true }
serde_macros = { version = "0.4", optional = true }

[dev-dependencies]
cfg-if = "0.1"

[features]

doc = []
